---
- name: Download mitmproxy via Git
  include_role:
    name: git_cached
  vars:
    repo: https://github.com/mitmproxy/mitmproxy.git
    dest: "{{ mitmproxy_install_path }}"

- import_tasks: "tasks/mark_installed.yml"