---
- include_tasks: "tasks/override.yml"
  when: override is defined

- name: Validate variables
  assert:
    that:
    - method is not defined or (method == "manual")

- name: Add python3.6 ppa to apt repos
  apt_repository:
    repo: ppa:jonathonf/python-3.6
    state: present

- name: Install apt package prerequisites
  apt:
    update_cache: yes
    name: python3.6

- import_tasks: "tasks/check_installed.yml"

- include_tasks: "install_manual.yml"
  when: (method is not defined or method == 'manual') and not installed

#- name: Test for command
#  shell: "command -v {{ cowpatty_install_path }}/cowpatty >/dev/null 2>&1"
#  register: is_installed
#  ignore_errors: yes
#
#- name: Test assertions
#  assert:
#    that:
#      - is_installed.rc == 0
#    fail_msg: "coWPAtty did not install correctly."