---
- name: Install apt package prerequisites
  apt:
    update_cache: yes
    name:
    - python3
    - python3-dev
    - python3-pip
    - libssl-dev
    - swig

- name: Install pip
  command: python3 -m pip install -U pip

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Download empire via Git
  git:
    repo: "{{ empire_url }}"
    version: "{{ empire_version}}"
    dest: "{{ empire_install_path }}"

- name: Install pip requirements
  pip:
    requirements: "{{ empire_install_path }}/setup/requirements.txt"
    virtualenv: "{{ empire_install_path }}/venv"
    virtualenv_python: python3

#- name: Install additional pip packages
#  pip:
#    name:
#    - pyOpenSSL
#    - pefile
#    - urllib3==1.22
#    - flask
#    - future
#    - iptools
#    - simplejson
#    virtualenv: "{{ empire_install_path }}/venv"

- name: Run empire installer
  shell: |
    . venv/bin/activate
    ./setup/install.sh <<EOF

    EOF
  args:
    chdir: "{{ empire_install_path }}"

- name: Create launcher script
  blockinfile:
    path: "{{ empire_install_path }}/empire-bootstrap.sh"
    create: yes
    mode: 0755
    block: |
      #!/bin/bash
      
      if [ $(/usr/bin/id -u) -ne 0 ]; then
          echo "Please run Empire as root."
          exit
      fi
      
      echo "Starting Empire..."
      
      cd {{ empire_install_path }}
      . venv/bin/activate
      ./empire "$@"
      
- name: Create Starkiller path
  file:
    path: "{{ empire_starkiller_install_path }}"
    state: directory
      
- name: Download Starkiller
  get_url:
    url: "{{ empire_starkiller_url }}"
    dest: "{{ empire_starkiller_install_path }}/"
    mode: 0755
  when: empire_starkiller_install

- name: Create symlink
  file:
    src: "{{ empire_install_path }}/empire-bootstrap.sh"
    dest: "{{ symlink_path }}/empire"
    state: link
  when: create_symlinks is defined and create_symlinks

- import_tasks: "tasks/mark_installed.yml"