---
- name: Install apt package prerequisites
  apt:
    name:
    - build-essential
    - debhelper
    - dh-systemd
    - libbladerf-dev
    - libncurses5-dev
    - librtlsdr-dev
    - pkg-config

- name: Download dump1090 via Git
  include_role:
    name: git_cached
  vars:
    repo: "{{ dump1090_url }}"
    version: "{{ dump1090_version}}"
    dest: "{{ dump1090_install_path }}"
    
- name: Build dump1090
  make:
    chdir: "{{ dump1090_install_path }}"
    
- name: Create symlink
  file:
    src: "{{ dump1090_install_path }}/{{ dump1090_item }}"
    dest: "{{ symlink_path }}/{{ dump1090_item }}"
    state: link
  loop:
  - dump1090
  - view1090
  loop_control:
    loop_var: dump1090_item
  when: create_symlinks is defined and create_symlinks
    
- import_tasks: "tasks/mark_installed.yml"