---
- include_tasks: "tasks/override.yml"
  when: override is defined

- name: Validate variables
  assert:
    that:
    - method is not defined or (method == "manual" or method == "local")
    
- name: Install apt package prerequisites
  apt:
    update_cache: yes
    name: openjdk-11-jdk
    
- import_tasks: "tasks/check_installed.yml"

- include_tasks: "install_local.yml"
  when: (method is not defined or method == 'local') and not installed

- import_tasks: "tasks/check_installed.yml"

- include_tasks: "install_manual.yml"
  when: (method is not defined or method == 'manual') and not installed