---
- name: Install apt package prerequisites
  apt:
    name:
    - build-essential

- name: Download crackle via Git
  include_role:
    name: git_cached
  vars:
    repo: "{{ crackle_url }}"
    version: "{{ crackle_version}}"
    dest: "{{ crackle_install_path }}"
    
- name: Build crackle
  make:
    chdir: "{{ crackle_install_path }}"
    
- name: Install crackle
  make:
    chdir: "{{ crackle_install_path }}"
    target: install
    
- import_tasks: "tasks/mark_installed.yml"