---
- include_tasks: "tasks/override.yml"
  when: override is defined

- import_tasks: "tasks/check_installed.yml"

- include_tasks: "install_manual.yml"
  when: (method is not defined or method == 'manual') and not installed

- include_tasks: "tasks/test.yml"
  vars:
    command: eql