---
- name: Install apt package prerequisites
  apt:
    name:
    - python3
    - python3-dev
    - python3-pip

- name: Install cliff
  pip:
    name: cliff
    executable: pip3
    
- name: Install faction
  shell: "curl https://raw.githubusercontent.com/FactionC2/Faction/master/install.sh | bash"
  ignore_errors: yes
  args:
    warn: false

- name: Add initialization to post-root.sh script
  lineinfile:
    path: "{{ user_home }}/post-root.sh"
    line: "faction setup"
    insertafter: "^### START ROLE-SPECIFIC TASKS$"

- import_tasks: "tasks/mark_installed.yml"