---
- name: Install apt package prerequisites
  apt:
    name:
    - curl
    - git
    - gnupg
    - python
    - python-pip

- name: Install pexpect Python module
  pip:
    name: pexpect
    state: present
  
- block:
  - name: Install RVM GPG keys
    shell: gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  
  - name: Install RVM without dependencies
    shell: curl -sSL https://get.rvm.io | bash -s -- --autolibs=install-packages
    args:
      warn: no
  become: yes
  become_user: "{{ user_name }}"
  
- name: Install RVM dependencies
  shell: .rvm/bin/rvm requirements 
  args:
    chdir: "{{ user_home }}"
    
- name: Checkout latest BeEF code
  include_role:
    name: git_cached
  vars:
    repo: https://github.com/beefproject/beef.git
    version: "{{ beef_version }}"
    dest: "{{ beef_install_path }}"
    
- name: Create beef group
  group:
    name: beef
    state: present
    
- name: Adding user to beef group 
  user:
    name: "{{ user_name }}"
    groups: beef
    append: yes
    
- name: Change ownership of beef install directory
  file:
    path: "{{ beef_install_path }}"
    group: beef
    mode: g+w
    recurse: yes
    
- block:
  - name: Install RVM with dependencies
    shell: curl -sSL https://get.rvm.io | bash -s stable --ruby
    args:
      warn: no
      
  - name: Install Ruby
    shell: source ~/.profile && rvm install ruby-2.5.3
    args:
      executable: /bin/bash

  - name: Install BeEF
    shell: source ~/.profile && yes | ./install
    args:
      chdir: "{{ beef_install_path }}"
      executable: /bin/bash
  become: yes
  become_user: "{{ user_name }}"
  
- name: Create launcher script
  blockinfile:
    path: "{{ beef_install_path }}/beef-bootstrap.sh"
    create: yes
    mode: 0775
    block: |
      #!/bin/bash

      echo "Starting BeEF..." 
      cd {{ beef_install_path }} && ruby-rvm-env beef "$@"
    
- name: Create symlink
  file:
    src: "{{ beef_install_path}}/beef-bootstrap.sh"
    dest: "{{ symlink_path }}/beef"
    state: link
  when: create_symlinks is defined and create_symlinks

- import_tasks: "tasks/mark_installed.yml"