---
- include_tasks: "tasks/override.yml"
  when: override is defined

- name: Validate variables
  assert:
    that:
    - method is not defined or (method == "apt")

- import_tasks: "tasks/check_installed.yml"

- include_tasks: "install_apt.yml"
  when: (method is not defined or method == 'apt') and not installed

- name: Start MongoDB service
  service:
    name: mongod
    state: started

#- name: Test for command
#  shell: "command -v {{ cowpatty_install_path }}/cowpatty >/dev/null 2>&1"
#  register: is_installed
#  ignore_errors: yes
#
#- name: Test assertions
#  assert:
#    that:
#      - is_installed.rc == 0
#    fail_msg: "coWPAtty did not install correctly."

