---
- name: Install apt package prerequisites
  apt:
    name:
    - git
    - python3
    - python3-venv
    - python3-pip

- name: Install virtualenv
  pip:
    name:
    - pexpect
    - virtualenv

- name: Checkout latest weirdAAL code
  include_role:
    name: git_cached
  vars:
    repo: https://github.com/carnal0wnage/weirdAAL.git
    dest: "{{ weirdaal_install_path }}"

- name: Install pip requirements
  pip:
    requirements: "{{ weirdaal_install_path }}/requirements.txt"
    virtualenv: "{{ weirdaal_install_path }}/venv"
    virtualenv_python: python3
    
- name: Create weirdAAL database
  expect:
    chdir: "{{ weirdaal_install_path }}"
    command: "/bin/bash -c '. venv/bin/activate && python3 create_dbs.py'"
    responses:
      do you wish to recreate it: "y"
    echo: yes
    timeout: null

- name: Create launcher script
  blockinfile:
    path: "{{ weirdaal_install_path }}/weirdaal-bootstrap.sh"
    create: yes
    mode: 0755
    block: |
      #!/bin/bash
      #!/bin/bash
      if [ $(/usr/bin/id -u) -ne 0 ]; then
          echo "Please run weirdAAL as root."
          exit
      fi
      
      cd {{ weirdaal_install_path }}
      . venv/bin/activate
      python weirdAAL.py "$@"

- name: Create symlink
  file:
    src: "{{ weirdaal_install_path }}/weirdaal-bootstrap.sh"
    dest: "{{ symlink_path }}/weirdaal"
    state: link
  when: create_symlinks is defined and create_symlinks

- import_tasks: "tasks/mark_installed.yml"