---
- name: Install apt package prerequisites
  apt:
    name:
    - bluetooth
    - bluez
    - libbluetooth-dev
    - libudev-dev
    - nodejs

- include_role:
    name: install_modules
  vars:
    npm_modules:
    - bleno
    - noble
    - gattacker

- import_tasks: "tasks/mark_installed.yml"