---
- name: Install apt package prerequisites
  apt:
    name:
    - git
    - python
    - python-pip
    - python-xlsxwriter
    - python-crypto
    - python-mechanize

- name: Download recon-ng via Git
  git:
    repo: https://github.com/lanmaster53/recon-ng.git
    version: "{{ reconng_version}}"
    dest: "{{ reconng_install_path }}"

- name: Install pip
  command: python -m pip install -U pip

- name: Downgrade pip to 9.0.3
  command: python -m pip install 'pip==9.0.3' --force-reinstall

- name: Install requirements via pip
  pip:
    requirements: "{{ reconng_install_path }}/REQUIREMENTS"

- import_tasks: "tasks/mark_installed.yml"