---
- name: Install apt package prerequisites
  apt:
    name:
    - python3
    - python3-pip

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Download impacket via Git
  git:
    repo: https://github.com/SecureAuthCorp/impacket.git
    dest: "{{ impacket_install_path }}"

- name: Install pip requirements
  shell: "pip install ."
  args:
    chdir: "{{ impacket_install_path }}"

- import_tasks: "tasks/mark_installed.yml"