---
- name: Install apt package prerequisites
  apt:
    name:
    - build-essential
    - libbluetooth-dev

- name: Download bss via Git
  include_role:
    name: git_cached
  vars:
    repo: "{{ bss_url }}"
    version: "{{ bss_version}}"
    dest: "{{ bss_install_path }}"
    
- name: Build bss
  make:
    chdir: "{{ bss_install_path }}"
    
- name: Install bss
  make:
    chdir: "{{ bss_install_path }}"
    target: install
    
- import_tasks: "tasks/mark_installed.yml"