---
- name: Install apt package prerequisites
  apt:
    name:
    - python
    - python-dev
    - python-pip
    - libssl-dev
    - swig

- name: Install pip
  command: python -m pip install -U pip

- name: Downgrade pip to 9.0.3
  command: python -m pip install 'pip==9.0.3' --force-reinstall

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Download empire via Git
  git:
    repo: "{{ empire_url }}"
    version: "{{ empire_version}}"
    dest: "{{ empire_install_path }}"

- name: Install pip requirements
  pip:
    requirements: "{{ empire_install_path }}/setup/requirements.txt"
    virtualenv: "{{ empire_install_path }}/venv"
    virtualenv_python: python2

- name: Install additional pip packages
  pip:
    name:
    - pyOpenSSL
    - pefile
    - urllib3==1.22
    virtualenv: "{{ empire_install_path }}/venv"

- name: Run empire installer
  shell: |
    . venv/bin/activate
    ./setup/install.sh <<EOF

    EOF
  args:
    chdir: "{{ empire_install_path }}"

- name: Reinstall pip
  command: python -m pip install pip --force-reinstall

- name: Create launcher script
  blockinfile:
    path: "{{ empire_install_path }}/empire-bootstrap.sh"
    create: yes
    mode: 0755
    block: |
      #!/bin/bash
      
      if [ $(/usr/bin/id -u) -ne 0 ]; then
          echo "Please run Empire as root."
          exit
      fi
      
      echo "Starting Empire..."
      
      cd {{ empire_install_path }}
      . venv/bin/activate
      ./empire "$@"

- name: Create symlink
  file:
    src: "{{ empire_install_path }}/empire-bootstrap.sh"
    dest: "{{ symlink_path }}/empire"
    state: link
  when: create_symlinks is defined and create_symlinks

- import_tasks: "tasks/mark_installed.yml"