---
- name: Install apt package prerequisites
  apt:
    name:
    - build-essential
    - gcc-arm-none-eabi
    - git
    - libncurses5-dev
    - libpcsclite-dev
    - libqt4-dev
    - libreadline-dev
    - libreadline5
    - libstdc++-arm-none-eabi-newlib
    - libusb-0.1-4
    - libusb-dev
    - p7zip
    - pcscd
    - perl
    - pkg-config
    - wget

- name: Download proxmark3 via Git
  include_role:
    name: git_cached
  vars:
    repo: "{{ proxmark3_url }}"
    version: "{{ proxmark3_version}}"
    dest: "{{ proxmark3_install_path }}"
    
- name: Build proxmark3
  make:
    chdir: "{{ proxmark3_install_path }}"
    target: all
    
- name: Create client symlinks
  file:
    src: "{{ proxmark3_install_path }}/client/{{ proxmark3_item }}"
    dest: "{{ symlink_path }}/{{ proxmark3_item }}"
    state: link
  loop:
  - flasher
  - fpga_compress
  - proxmark3
  - unbind-proxmark
  loop_control:
    loop_var: proxmark3_item
  when: create_symlinks is defined and create_symlinks
    
- import_tasks: "tasks/mark_installed.yml"